version: '2.12.2'
services:

  mongo-db:
    image: mongo
    restart: always
    container_name: mongoxml
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: 123

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoxml-express
    ports:
      - 8081:8081
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adm
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongo-db